# Auto-generated by deploy-infra.sh on 2026-02-17T23:49:05Z
# Source this file to set infrastructure environment variables:
#   source infrastructure/config.sh

export S3_BUCKET="runbook-artifacts-production"
export CLOUDFRONT_DISTRIBUTION_ID="E2AQARPOCQN7V8"
export ARTIFACTS_URL="https://runbookmcp.dev"
export DEPLOY_USER_NAME="runbook-deploy-production"
