# Auto-generated by infrastructure/deploy.sh on 2026-03-09T19:47:05Z
# Source this file to set artifact environment variables:
#   source infrastructure/config.sh

export STORAGE_ACCOUNT="runbookproduction"
export CONTAINER_NAME='$web'
export ARTIFACTS_URL="https://runbookproduction.z13.web.core.windows.net/"
export BLOB_ENDPOINT="https://runbookproduction.blob.core.windows.net/"
export SWA_NAME="runbook-website-production"
export WEBSITE_URL="https://yellow-flower-06cd9aa0f.4.azurestaticapps.net"
export DEPLOYMENT_TOKEN="a6d3ba18a9dd08d443eac615e450e8f7954ad0ee58a57365f4d68ed579e623c804-3f863fa3-ac86-483d-9588-0445295b78ad00f132906cd9aa0f"
export TENANT_ID="01ea369a-621c-4b70-a22c-b9c52c2076d4"
