#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# deploy-infra.sh - Deploy CloudFormation stack for runbook.dev infrastructure
#
# Usage: ./infrastructure/deploy-infra.sh [--env ENV] [--cert-arn ARN]
#
# Flags:
#   --env ENV       Environment name (default: production)
#   --cert-arn ARN  ACM certificate ARN in us-east-1 (required)
#
# Prerequisites:
#   - AWS CLI authenticated
#   - ACM certificate pre-created in us-east-1
#
# Writes infrastructure/config.sh after successful deploy.
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.sh"
TEMPLATE_FILE="${SCRIPT_DIR}/cloudformation.yaml"
REGION="us-west-2"

ENV="production"
CERT_ARN=""

while [ $# -gt 0 ]; do
  case "$1" in
    --env)
      ENV="$2"
      shift 2
      ;;
    --cert-arn)
      CERT_ARN="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

STACK_NAME="runbook-${ENV}"

echo "============================================"
echo "  Runbook - Infrastructure Deploy"
echo "============================================"
echo ""
echo "Stack     : ${STACK_NAME}"
echo "Region    : ${REGION}"
echo "Env       : ${ENV}"
echo ""

PARAMS="ParameterKey=Environment,ParameterValue=${ENV}"
if [ -n "$CERT_ARN" ]; then
  PARAMS="${PARAMS} ParameterKey=AcmCertificateArn,ParameterValue=${CERT_ARN}"
fi

echo "Deploying CloudFormation stack..."
aws cloudformation deploy \
  --region "${REGION}" \
  --stack-name "${STACK_NAME}" \
  --template-file "${TEMPLATE_FILE}" \
  --parameter-overrides ${PARAMS} \
  --capabilities CAPABILITY_IAM \
  --no-fail-on-empty-changeset

echo "Stack deployed successfully."
echo ""

echo "Retrieving outputs..."
BUCKET_NAME=$(aws cloudformation describe-stacks \
  --region "${REGION}" \
  --stack-name "${STACK_NAME}" \
  --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
  --output text)

DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
  --region "${REGION}" \
  --stack-name "${STACK_NAME}" \
  --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" \
  --output text)

DEPLOY_USER=$(aws cloudformation describe-stacks \
  --region "${REGION}" \
  --stack-name "${STACK_NAME}" \
  --query "Stacks[0].Outputs[?OutputKey=='DeployUserName'].OutputValue" \
  --output text)

echo "  Bucket             : ${BUCKET_NAME}"
echo "  Distribution ID    : ${DISTRIBUTION_ID}"
echo "  Deploy User        : ${DEPLOY_USER}"
echo ""

echo "Writing config to '${CONFIG_FILE}'..."
cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by deploy-infra.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source this file to set infrastructure environment variables:
#   source infrastructure/config.sh

export S3_BUCKET="${BUCKET_NAME}"
export CLOUDFRONT_DISTRIBUTION_ID="${DISTRIBUTION_ID}"
export ARTIFACTS_URL="https://runbook.dev"
export DEPLOY_USER_NAME="${DEPLOY_USER}"
EOF

echo "Config written. Source it with:"
echo "  source infrastructure/config.sh"
echo ""
echo "============================================"
echo "  Deployment complete!"
echo "============================================"
